# Generated by Django 5.1.4 on 2025-07-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profie_img',
            new_name='profile_img',
        ),
    ]
