# Generated by Django 5.1.4 on 2025-07-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_subscribe_user_alter_subscribe_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
